-- reverse of 001_initial.up.sql
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS detections CASCADE;
DROP TABLE IF EXISTS recordings CASCADE;
DROP TABLE IF EXISTS snapshots CASCADE;
DROP TABLE IF EXISTS cameras CASCADE;
